# app
app:
  name: "Magician"

# server
server:
  address: ':6954'
  readTimeout: 10
  writeTimeout: 10

# logger configuration
log:
  prefix: '[magician]'
  logFile: true
  stdout: 'DEBUG'
  file: 'DEBUG'
  logSoftLink: './.log/latest_log'
  logDir: './.log'

# gorm config
gorm:
  # 是否开启调试模式
  debug: true
  # 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
  dbType: 'mysql'
  # 设置连接可以重用的最长时间(单位：秒)
  maxLifetime: 7200
  # 设置数据库的最大打开连接数
  maxOpenConns: 150
  # 设置空闲连接池中的最大连接数
  maxIdleConns: 50
  # 是否启用自动映射数据库表结构
  enableAutoMigrate: true

# mysql config
mysql:
  # 连接地址
  host: "127.0.0.1"
  # 连接端口
  port: 3306
  # 用户名
  user: "root"
  # 密码
  password: "password"
  # 数据库
  dbName: "db_name"
  # 连接参数
  parameters: "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
  # string 类型字段的默认长度
  defaultStringSize: 256
  # 禁用 datetime 精度，MySQL 5.6 之前的数据库不支持
  disableDatetimePrecision: true
  # 重命名索引时采用删除并新建的方式，MySQL 5.7 之前的数据库和 MariaDB 不支持重命名索引
  dontSupportRenameIndex: true
  # 用 `change` 重命名列，MySQL 8 之前的数据库和 MariaDB 不支持重命名列
  dontSupportRenameColumn: true
  # 根据当前 MySQL 版本自动配置
  skipInitializeWithVersion: false

# redis config
redis:
  address: "127.0.0.1:6379"
  db: 4
  password: "password"
  keyPrefix: "pre:"