# server
server:
  address: ':6954'
  readTimeout: 10
  writeTimeout: 10

# logger configuration
log:
  prefix: '[MAGICIAN]'
  logFile: true
  stdout: 'DEBUG'
  file: 'DEBUG'
  logSoftLink: './.log/latest_log'
  logDir: './.log'